#!/bin/bash
export MSYS_NO_PATHCONV=1
SCRIPT_HOME="$( cd "$( dirname "$0" )" && pwd )"

toLower() {
  echo $(echo ${@} | tr '[:upper:]' '[:lower:]')
}

echoWarning (){
  _msg=${@}
  _yellow='\033[1;33m'
  _nc='\033[0m' # No Color
  echo -e "${_yellow}${_msg}${_nc}" >&2
}

echoError (){
  _msg=${@}
  _red='\033[0;31m'
  _nc='\033[0m' # No Color
  echo -e "${_red}${_msg}${_nc}" >&2
}

printAndWaitForYes() {
  _msg=${@}
  if [ -z "${_msg}" ]; then
    echo -e \\n"printAndWaitForYes; Missing parameter!"\\n
    exit 1
  fi

  echoWarning "\n${_msg}"
  read -r -p $'\e[33mWould you like to continue? [y/n]\e[0m ' response
  echo
  # https://stackoverflow.com/a/3232082
  if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    return 0
  else
    return 1
  fi
}

function isInstalled () {
  rtnVal=$(type "$1" >/dev/null 2>&1)
  rtnCd=$?
  if [ ${rtnCd} -ne 0 ]; then
    return 1
  else
    return 0
  fi
}

function isCurlInstalled () {
  CURL_EXE=curl
  if ! isInstalled ${CURL_EXE}; then
    echoError "The ${CURL_EXE} executable is required and was not found on your path."
    echoError "If your shell of choice doesn't come with curl preinstalled, try installing it using either [Homebrew](https://brew.sh/) (MAC) or [Chocolatey](https://chocolatey.org/) (Windows)."
    exit 1
  fi
}

function isJQInstalled () {
  JQ_EXE=jq
  if ! isInstalled ${JQ_EXE}; then
    echoError "The ${JQ_EXE} executable is required and was not found on your path."
    echoError "Installation instructions can be found here: https://stedolan.github.io/jq/download"
    echoError "Alternatively, a package manager such as Chocolatey (Windows) or Brew (Mac) can be used to install this dependecy."
    exit 1
  fi
}

# =================================================================================================================
# Usage:
# -----------------------------------------------------------------------------------------------------------------
usage () {
  cat <<-EOF
  Functions to copy and delete IDPs and their mappers within KeyCloak realms.

  Usage:
    $0 [options] [commands]

    With all of the commands specifying the source and/or destination client credentials is optional.
    If not provided on the command line, you will be asked for them when they are needed.

  Commands:
  ========
    copyIdpAndMappers <sourceBaseUrl> <sourceRealm> <destBaseUrl> <destRealm> <idpName>
      - Copy an IDP and its mappers from one KeyCloak environment to another.

      Example:
        sourceClientId="migration-user" \
        sourceClientSecret=<Source_Client_Credentials> \
        destClientId="migration-user" \
        destClientSecret=<Destination_Client_Credentials> \
        ./manage copyIdpAndMappers \
          "https://dev.oidc.gov.bc.ca" \
          "gzyg46lx" \
          "https://dev.loginproxy.gov.bc.ca" \
          "digitaltrust-citz" \
          "bcsc"

    copyClientAndRoles <sourceBaseUrl> <sourceRealm> <destBaseUrl> <destRealm> <clientId>
      - Copy a Client its mappers, and roles from one KeyCloak environment to another.

      Example:
        sourceClientId="migration-user" \
        sourceClientSecret=<Source_Client_Credentials> \
        destClientId="migration-user" \
        destClientSecret=<Destination_Client_Credentials> \
        ./manage copyClientAndRoles \
          "https://dev.oidc.gov.bc.ca" \
          "tz0e228w" \
          "https://dev.loginproxy.gov.bc.ca" \
          "court-services-jag" \
          "ai-reviewer-api"

    copyIdp <sourceBaseUrl> <sourceRealm> <destBaseUrl> <destRealm> <idpName>
      - Copy an IDP from one KeyCloak environment to another.
      - See copyIdpAndMappers for an example

    copyIdpMappers <sourceBaseUrl> <sourceRealm> <destBaseUrl> <destRealm> <idpName>
      - Copy the mappers from one IDP to another.  The IDP must already exist.
      - See copyIdpAndMappers for an example

    deleteIdp <baseUrl> <realm> <idpName>
      - Delete an IDP from a realm.

      Example:
        clientId="migration-user" \
        clientSecret=<Client_Credentials> \
        ./manage deleteIdp \
          "https://dev.loginproxy.gov.bc.ca" \
          "digitaltrust-citz" \
          "bcsc"

    deleteidpmappers <baseUrl> <realm> <idpName>
      - Delete the mappers from an IDP.
      - See deleteIdp for an example.

    copyClient <sourceBaseUrl> <sourceRealm> <destBaseUrl> <destRealm> <clientId>
      - Copy a Client and its mappers from one KeyCloak environment to another.
      - See copyClientAndRoles for an example

    copyClientRoles <sourceBaseUrl> <sourceRealm> <destBaseUrl> <destRealm> <clientId>
      - Copy the roles from one Client to another.  The Client must already exist.
      - See copyClientAndRoles for an example

    getUsers <sourceBaseUrl> <sourceRealm> [<searchQuery>]
      - Gets a list of matching userIds.  Full user account information written out to ${USER_ACCOUNT_FILE}.

      Example - Get all VC users:
        clientId="migration-user" \
        clientSecret=<Client_Credentials> \
        ./manage getUsers \
          "https://dev.loginproxy.gov.bc.ca" \
          "access-to-court-materials-jag" \
          "%@vc"

    deleteUsers <sourceBaseUrl> <sourceRealm> [<searchQuery>]
      - Delete all matching userIds.  Full user account information written out to ${USER_ACCOUNT_FILE}.

      Example - Delete all VC users:
        clientId="migration-user" \
        clientSecret=<Client_Credentials> \
        ./manage deleteUsers \
          "https://dev.loginproxy.gov.bc.ca" \
          "access-to-court-materials-jag" \
          "%@vc"
EOF
}

function getTokenUrl() {
  baseUrl=${1}
  realm=${2}
  echo "${baseUrl}/auth/realms/${realm}/protocol/openid-connect/token"
}

function getAuthToken() {
  tokenUrl=${1}
  clientId=${2}
  clientSecret=${3}
  tokenName=${4}

  if [ -z ${tokenUrl} ] || [ -z ${tokenName} ]; then
    echoError "You MUST supply both 'tokenUrl' and 'tokenName' parameters."
    echoWarning "Usage - getAuthToken <tokenUrl> [clientId] [clientSecret] <tokenName>"
    return 1
  fi

  if [ -z "${clientId}" ]; then
    echo
    read -rep $"Please enter the client id for the connection to ${tokenUrl}:$(echo $'\n> ')" ${!clientId@}
  fi

  if [ -z "${clientSecret}" ]; then
    echo
    read -srep $"Please enter the client secret for '${clientId}' when connecting to ${tokenUrl}:$(echo $'\n> ')" ${!clientSecret@}
    echo -e "\n"
  fi

  echo -e "Retrieving auth token for '${clientId}' from ${tokenUrl} ..."
  tokenJson=$(${CURL_EXE} \
            -s \
            -X "POST" \
            -H "accept: application/json" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            --data-urlencode "grant_type=client_credentials" \
            --data-urlencode "client_id=${clientId}" \
            --data-urlencode "client_secret=${clientSecret}" \
            "${tokenUrl}")

  if [[ "${tokenJson}" == *"error"* ]]; then
    echoError "${tokenJson}"
    return 1
  fi

  export ${tokenName}="Authorization: $(${JQ_EXE} -nr "${tokenJson} | .token_type") $(${JQ_EXE} -nr "${tokenJson} | .access_token")"
}

function copyIdpAndMappers() {
  sourceBaseUrl=${1}
  sourceRealm=${2}
  sourceToken=${3}

  destBaseUrl=${4}
  destRealm=${5}
  destToken=${6}

  idpName=${7}

  copyIdp "${sourceBaseUrl}" \
          "${sourceRealm}" \
          "${sourceToken}" \
          "${destBaseUrl}" \
          "${destRealm}" \
          "${destToken}" \
          "${idpName}"

  if (( ${?} != 0 )); then
    if ! printAndWaitForYes "An error occured while copying the IDP.  Please review the error."; then
      exit 1
    fi
  fi

  copyIdpMappers "${sourceBaseUrl}" \
                  "${sourceRealm}" \
                  "${sourceToken}" \
                  "${destBaseUrl}" \
                  "${destRealm}" \
                  "${destToken}" \
                  "${idpName}"
}

function copyIdp() {
  sourceBaseUrl=${1}
  sourceRealm=${2}
  sourceToken=${3}

  destBaseUrl=${4}
  destRealm=${5}
  destToken=${6}

  idpName=${7}

  sourceIdpUrl="${sourceBaseUrl}/auth/admin/realms/${sourceRealm}/identity-provider/instances/${idpName}"
  destIdpUrl="${destBaseUrl}/auth/admin/realms/${destRealm}/identity-provider/instances"

  sourceIdp=$(${CURL_EXE} \
            -s \
            -X GET \
            -H "accept: application/json" \
            -H "${destToken}" \
            "${destIdpUrl}/${idpName}")

  if [[ "${sourceIdp}" != *"404 Not Found"* ]]; then
    echo -e "\nThe IDP, '${idpName}', already exists in ${destIdpUrl}."
    return 0
  fi

  sourceIdp=$(${CURL_EXE} \
            -s \
            -X GET \
            -H "accept: application/json" \
            -H "${sourceToken}" \
            "${sourceIdpUrl}")

  echo -e "\nCopying the '${idpName}' IDP from ${sourceIdpUrl} to ${destIdpUrl} ..."
  destPostIdpResponse=$(${CURL_EXE} \
                      -s \
                      -X POST \
                      -H "accept: application/json" \
                      -H "Content-Type: application/json" \
                      -H "${destToken}" \
                      --data-raw "${sourceIdp}" \
                      "${destIdpUrl}")

  if [[ "${destPostIdpResponse}" == *"error"* ]]; then
    echoError "${destPostIdpResponse}"
    return 1
  fi
}

function copyIdpMappers() {
  sourceBaseUrl=${1}
  sourceRealm=${2}
  sourceToken=${3}

  destBaseUrl=${4}
  destRealm=${5}
  destToken=${6}

  idpName=${7}

  sourceMapperUrl="${sourceBaseUrl}/auth/admin/realms/${sourceRealm}/identity-provider/instances/${idpName}/mappers"
  destMapperUrl="${destBaseUrl}/auth/admin/realms/${destRealm}/identity-provider/instances/${idpName}/mappers"

  sourceIdpMappers=$(${CURL_EXE} \
                      -s \
                      -X GET \
                      -H "accept: application/json" \
                      -H "${sourceToken}" \
                      "${sourceMapperUrl}")

  destIdpMappers=$(${CURL_EXE} \
                  -s \
                  -X GET \
                  -H "accept: application/json" \
                  -H "${destToken}" \
                  "${destMapperUrl}")

  echo
  sourceMapperCount=$(${JQ_EXE} -nr "${sourceIdpMappers} | length")
  for (( counter=0; counter<${sourceMapperCount}; counter++ )); do
    sourceIdpMapper=$(${JQ_EXE} -nrc "${sourceIdpMappers} | .[${counter}]")
    sourceIdpMapperName=$(${JQ_EXE} -nr "${sourceIdpMapper} | .name")

    destIdpMapper=$(${JQ_EXE} -nr "${destIdpMappers} | .[] | select(.name ==\"${sourceIdpMapperName}\")")
    if [ ! -z "${destIdpMapper}" ]; then
      echo -e "The '${sourceIdpMapperName}' mapper already exists in ${destMapperUrl}."
      continue
    fi

    echo "Copying mapper '${sourceIdpMapperName}' from ${sourceMapperUrl} to ${destMapperUrl} ..."
    destIdpPostMapperResponse=$(${CURL_EXE} \
                                -s \
                                -X POST \
                                -H "accept: application/json" \
                                -H "Content-Type: application/json" \
                                -H "${destToken}" \
                                --data-raw "${sourceIdpMapper}" \
                                "${destMapperUrl}")

    if [[ "${destIdpPostMapperResponse}" == *"error"* ]]; then
      echoError "${destIdpPostMapperResponse}"
      return 1
    fi
  done
}

function deleteIdp() {
  baseUrl=${1}
  realm=${2}
  token=${3}
  idpName=${4}
  idpUrl="${baseUrl}/auth/admin/realms/${realm}/identity-provider/instances/${idpName}"

  echo "Deleting IDP: ${idpName} ..."
  deleteIdpResponse=$(${CURL_EXE} \
                        -s \
                        -X DELETE  \
                        -H "accept: application/json" \
                        -H "${token}" \
                        "${idpUrl}")

  if [[ "${deleteIdpResponse}" == *"error"* ]]; then
    echoError "${deleteIdpResponse}"
    return 1
  fi
}

function deleteIdpMappers() {
  baseUrl=${1}
  realm=${2}
  token=${3}
  idpName=${4}
  mapperUrl="${baseUrl}/auth/admin/realms/${realm}/identity-provider/instances/${idpName}/mappers"

  idpMappers=$(${CURL_EXE} \
              -s \
              -X GET \
              -H "accept: application/json" \
              -H "${token}" \
              "${mapperUrl}")

  mapperCount=$(${JQ_EXE} -nr "${idpMappers} | length")
  if (( ${mapperCount}==0 )); then
    echoWarning "\nNothing to do.  The ${idpName} IDP does not contain any mappers."
  fi

  for (( counter=0; counter<${mapperCount}; counter++ )); do
    mapperId=$(${JQ_EXE} -nr "${idpMappers} | .[${counter}].id")
    mapperName=$(${JQ_EXE} -nr "${idpMappers} | .[${counter}].name")

    echo "Deleting IDP '${mapperName}' mapper from ${idpName} ..."
    deleteMapperResponse=$(${CURL_EXE} \
                          -s \
                          -X DELETE  \
                          -H "accept: application/json" \
                          -H "${token}" \
                          "${mapperUrl}/${mapperId}")

    if [[ "${deleteMapperResponse}" == *"error"* ]]; then
      echoError "${deleteMapperResponse}"
      return 1
    fi
  done
}

function copyClientAndRoles() {
  sourceBaseUrl=${1}
  sourceRealm=${2}
  sourceToken=${3}

  destBaseUrl=${4}
  destRealm=${5}
  destToken=${6}

  clientId=${7}

  copyClient "${sourceBaseUrl}" \
             "${sourceRealm}" \
             "${sourceToken}" \
             "${destBaseUrl}" \
             "${destRealm}" \
             "${destToken}" \
             "${clientId}"

  if (( ${?} != 0 )); then
    if ! printAndWaitForYes "An error occured while copying the Client.  Please review the error."; then
      exit 1
    fi
  fi

  copyClientRoles "${sourceBaseUrl}" \
                  "${sourceRealm}" \
                  "${sourceToken}" \
                  "${destBaseUrl}" \
                  "${destRealm}" \
                  "${destToken}" \
                  "${clientId}"
}

function copyClient() {
  sourceBaseUrl=${1}
  sourceRealm=${2}
  sourceToken=${3}

  destBaseUrl=${4}
  destRealm=${5}
  destToken=${6}

  clientId=${7}

  sourceClientId=$(getClientId \
                   "${sourceBaseUrl}" \
                   "${sourceRealm}" \
                   "${sourceToken}" \
                   "${clientId}")

  destClientId=$(getClientId \
                 "${destBaseUrl}" \
                 "${destRealm}" \
                 "${destToken}" \
                 "${clientId}")

  sourceClientUrl="${sourceBaseUrl}/auth/admin/realms/${sourceRealm}/clients/${sourceClientId}"
  destClientUrl="${destBaseUrl}/auth/admin/realms/${destRealm}/clients"

  if [ ! -z "${destClientId}" ]; then
    echo -e "\nThe Client, '${clientId}', already exists in ${destClientUrl}."
    return 0
  fi

  sourceClient=$(${CURL_EXE} \
               -s \
               -X GET \
               -H "accept: application/json" \
               -H "${sourceToken}" \
               "${sourceClientUrl}")

  echo -e "\nCopying the '${clientId}' Client from ${sourceClientUrl} to ${destClientUrl} ..."
  destPostClientResponse=$(${CURL_EXE} \
                         -s \
                         -X POST \
                         -H "accept: application/json" \
                         -H "Content-Type: application/json" \
                         -H "${destToken}" \
                         --data-raw "${sourceClient}" \
                         "${destClientUrl}")

  if [[ "${destPostClientResponse}" == *"error"* ]]; then
    echoError "${destPostClientResponse}"
    return 1
  fi
}

function copyClientRoles() {
  sourceBaseUrl=${1}
  sourceRealm=${2}
  sourceToken=${3}

  destBaseUrl=${4}
  destRealm=${5}
  destToken=${6}

  clientId=${7}

  sourceClientId=$(getClientId \
                   "${sourceBaseUrl}" \
                   "${sourceRealm}" \
                   "${sourceToken}" \
                   "${clientId}")

  destClientId=$(getClientId \
                 "${destBaseUrl}" \
                 "${destRealm}" \
                 "${destToken}" \
                 "${clientId}")

  sourceClientRolesUrl="${sourceBaseUrl}/auth/admin/realms/${sourceRealm}/clients/${sourceClientId}/roles"
  destClientRolesUrl="${destBaseUrl}/auth/admin/realms/${destRealm}/clients/${destClientId}/roles"

  if [ -z "${destClientId}" ]; then
    echo -e "\nThe Client, '${clientId}', does not exist in ${destBaseUrl}/auth/admin/realms/${destRealm}/clients."
    return 0
  fi

  sourceClientRoles=$(${CURL_EXE} \
                    -s \
                    -X GET \
                    -H "accept: application/json" \
                    -H "${sourceToken}" \
                    "${sourceClientRolesUrl}")

  destClientRoles=$(${CURL_EXE} \
                  -s \
                  -X GET \
                  -H "accept: application/json" \
                  -H "${destToken}" \
                  "${destClientRolesUrl}")

  echo
  sourceClientRoleCount=$(${JQ_EXE} -nr "${sourceClientRoles} | length")
  for (( counter=0; counter<${sourceClientRoleCount}; counter++ )); do
    sourceClientRole=$(${JQ_EXE} -nrc "${sourceClientRoles} | .[${counter}]")
    sourceClientRoleName=$(${JQ_EXE} -nr "${sourceClientRole} | .name")

    destClientRole=$(${JQ_EXE} -nr "${destClientRoles} | .[] | select(.name ==\"${sourceClientRoleName}\")")
    if [ ! -z "${destClientRole}" ]; then
      echo -e "The '${sourceClientRoleName}' client role already exists in ${destClientRolesUrl}."
      continue
    fi

    echo "Copying client role '${sourceClientRoleName}' from ${sourceClientRolesUrl} to ${destClientRolesUrl} ..."
    destClientRolesPostResponse=$(${CURL_EXE} \
                                -s \
                                -X POST \
                                -H "accept: application/json" \
                                -H "Content-Type: application/json" \
                                -H "${destToken}" \
                                --data-raw "${sourceClientRole}" \
                                "${destClientRolesUrl}")

    if [[ "${destClientRolesPostResponse}" == *"error"* ]]; then
      echoError "${destClientRolesPostResponse}"
      return 1
    fi
  done
}

function getClientId() {
  sourceBaseUrl=${1}
  sourceRealm=${2}
  sourceToken=${3}

  clientId=${4}

  sourceClientsUrl="${sourceBaseUrl}/auth/admin/realms/${sourceRealm}/clients"
  sourceClients=$(${CURL_EXE} \
                -s \
                -X GET \
                -H "accept: application/json" \
                -H "${sourceToken}" \
                "${sourceClientsUrl}")

  # Write results to a file, as they can be too long for direct input into jq.
  echo "${sourceClients}" > clients.json
  clientId=$(${JQ_EXE} -r ".[] | select(.clientId ==\"${clientId}\") | .id" clients.json)
  echo "${clientId}"
}

export USER_ACCOUNT_FILE="users.json"

function getUsers() {
  sourceBaseUrl=${1}
  sourceRealm=${2}
  sourceToken=${3}
  searchQuery=${4}

  sourceUsersUrl="${sourceBaseUrl}/auth/admin/realms/${sourceRealm}/users"
  sourceUsers=$(${CURL_EXE} \
                -s \
                -X GET \
                -G \
                -H "accept: application/json" \
                -H "${sourceToken}" \
                --data-urlencode "search=${searchQuery}" \
                --data-urlencode "max=1000" \
                "${sourceUsersUrl}")

  # Write results to a file, as they can be too long for direct input into jq.
  echo "${sourceUsers}" > ${USER_ACCOUNT_FILE}
  userIds=$(${JQ_EXE} -r ".[] | .id" ${USER_ACCOUNT_FILE})
  echo "${userIds}"
}

function deleteUsers() {
  sourceBaseUrl=${1}
  sourceRealm=${2}
  sourceToken=${3}
  searchQuery=${4}

  userIds=$(getUsers "${sourceBaseUrl}" \
                     "${sourceRealm}" \
                     "${sourceToken}" \
                     "${searchQuery}")

  userIdCount=$(echo "${userIds}" | wc -l)

  if (( ${userIdCount} <= 0 )); then
    echo "No matching accounts found."
    exit 0
  fi

  if printAndWaitForYes "Are you sure you want to delete ${userIdCount} user accounts?\nPlease review the accounts listed in ${USER_ACCOUNT_FILE} before you continue."; then
    for userId in ${userIds}; do
      userId=$(echo "${userId}" | tr -d '[:blank:]')
      echo -e "Deleting user account ${userId} ..."

      deleteUsersUrl="${sourceBaseUrl}/auth/admin/realms/${sourceRealm}/users"
      deleteUserResponse=$(${CURL_EXE} \
                          -s \
                          -X DELETE \
                          -H "accept: application/json" \
                          -H "${sourceToken}" \
                          "${deleteUsersUrl}/${userId}")

      if [[ "${deleteUserResponse}" == *"error"* ]]; then
        echoError "${deleteUserResponse}"
        return 1
      fi
    done
  else
    echo "Good Bye"
  fi
}
# =================================================================================================================

pushd ${SCRIPT_HOME} >/dev/null
_cmd=$(toLower ${1})
shift

case "${_cmd}" in
  copyidpandmappers)
    isCurlInstalled
    isJQInstalled

    sourceBaseUrl=${1:-https://dev.oidc.gov.bc.ca}
    sourceRealm=${2:-gzyg46lx}
    sourceToken=""
    tokenUrl=$(getTokenUrl "${sourceBaseUrl}" "${sourceRealm}")
    getAuthToken "${tokenUrl}" "${sourceClientId}" "${sourceClientSecret}" "${!sourceToken@}"

    destBaseUrl=${3:-https://dev.loginproxy.gov.bc.ca}
    destRealm=${4:-digitaltrust-citz}
    destToken=""
    tokenUrl=$(getTokenUrl "${destBaseUrl}" "${destRealm}")
    getAuthToken "${tokenUrl}" "${destClientId}" "${destClientSecret}" "${!destToken@}"

    idpName=${5:-bcsc}

    copyIdpAndMappers "${sourceBaseUrl}" \
                      "${sourceRealm}" \
                      "${sourceToken}" \
                      "${destBaseUrl}" \
                      "${destRealm}" \
                      "${destToken}" \
                      "${idpName}"
    ;;

  copyidp)
    isCurlInstalled
    isJQInstalled

    sourceBaseUrl=${1:-https://dev.oidc.gov.bc.ca}
    sourceRealm=${2:-gzyg46lx}
    sourceToken=""
    tokenUrl=$(getTokenUrl "${sourceBaseUrl}" "${sourceRealm}")
    getAuthToken "${tokenUrl}" "${sourceClientId}" "${sourceClientSecret}" "${!sourceToken@}"

    destBaseUrl=${3:-https://dev.loginproxy.gov.bc.ca}
    destRealm=${4:-digitaltrust-citz}
    destToken=""
    tokenUrl=$(getTokenUrl "${destBaseUrl}" "${destRealm}")
    getAuthToken "${tokenUrl}" "${destClientId}" "${destClientSecret}" "${!destToken@}"

    idpName=${5:-bcsc}

    copyIdp "${sourceBaseUrl}" \
            "${sourceRealm}" \
            "${sourceToken}" \
            "${destBaseUrl}" \
            "${destRealm}" \
            "${destToken}" \
            "${idpName}"
    ;;

  copyidpmappers)
    isCurlInstalled
    isJQInstalled

    sourceBaseUrl=${1:-https://dev.oidc.gov.bc.ca}
    sourceRealm=${2:-gzyg46lx}
    sourceToken=""
    tokenUrl=$(getTokenUrl "${sourceBaseUrl}" "${sourceRealm}")
    getAuthToken "${tokenUrl}" "${sourceClientId}" "${sourceClientSecret}" "${!sourceToken@}"

    destBaseUrl=${3:-https://dev.loginproxy.gov.bc.ca}
    destRealm=${4:-digitaltrust-citz}
    destToken=""
    tokenUrl=$(getTokenUrl "${destBaseUrl}" "${destRealm}")
    getAuthToken "${tokenUrl}" "${destClientId}" "${destClientSecret}" "${!destToken@}"

    idpName=${5:-bcsc}

    copyIdpMappers "${sourceBaseUrl}" \
                   "${sourceRealm}" \
                   "${sourceToken}" \
                   "${destBaseUrl}" \
                   "${destRealm}" \
                   "${destToken}" \
                   "${idpName}"
    ;;

  deleteidp)
    isCurlInstalled
    isJQInstalled

    baseUrl=${1:-https://dev.loginproxy.gov.bc.ca}
    realm=${2:-digitaltrust-citz}
    token=""
    tokenUrl=$(getTokenUrl "${baseUrl}" "${realm}")
    getAuthToken "${tokenUrl}" "${clientId}" "${clientSecret}" "${!token@}"

    idpName=${3:-bcsc}

    deleteIdp "${baseUrl}" \
              "${realm}" \
              "${token}" \
              "${idpName}"
    ;;

  deleteidpmappers)
    isCurlInstalled
    isJQInstalled

    baseUrl=${1:-https://dev.loginproxy.gov.bc.ca}
    realm=${2:-digitaltrust-citz}
    token=""
    tokenUrl=$(getTokenUrl "${baseUrl}" "${realm}")
    getAuthToken "${tokenUrl}" "${clientId}" "${clientSecret}" "${!token@}"

    idpName=${3:-bcsc}

    deleteIdpMappers "${baseUrl}" \
                     "${realm}" \
                     "${token}" \
                     "${idpName}"
    ;;

  copyclientandroles)
    isCurlInstalled
    isJQInstalled

    sourceBaseUrl=${1:-https://dev.oidc.gov.bc.ca}
    sourceRealm=${2:-tz0e228w}
    sourceToken=""
    tokenUrl=$(getTokenUrl "${sourceBaseUrl}" "${sourceRealm}")
    getAuthToken "${tokenUrl}" "${sourceClientId}" "${sourceClientSecret}" "${!sourceToken@}"

    destBaseUrl=${3:-https://dev.loginproxy.gov.bc.ca}
    destRealm=${4:-court-services-jag}
    destToken=""
    tokenUrl=$(getTokenUrl "${destBaseUrl}" "${destRealm}")
    getAuthToken "${tokenUrl}" "${destClientId}" "${destClientSecret}" "${!destToken@}"

    clientId=${5:-ai-reviewer-api}

    copyClientAndRoles "${sourceBaseUrl}" \
                       "${sourceRealm}" \
                       "${sourceToken}" \
                       "${destBaseUrl}" \
                       "${destRealm}" \
                       "${destToken}" \
                       "${clientId}"
    ;;

  copyclient)
    isCurlInstalled
    isJQInstalled

    sourceBaseUrl=${1:-https://dev.oidc.gov.bc.ca}
    sourceRealm=${2:-tz0e228w}
    sourceToken=""
    tokenUrl=$(getTokenUrl "${sourceBaseUrl}" "${sourceRealm}")
    getAuthToken "${tokenUrl}" "${sourceClientId}" "${sourceClientSecret}" "${!sourceToken@}"

    destBaseUrl=${3:-https://dev.loginproxy.gov.bc.ca}
    destRealm=${4:-court-services-jag}
    destToken=""
    tokenUrl=$(getTokenUrl "${destBaseUrl}" "${destRealm}")
    getAuthToken "${tokenUrl}" "${destClientId}" "${destClientSecret}" "${!destToken@}"

    clientId=${5:-ai-reviewer-api}

    copyClient "${sourceBaseUrl}" \
               "${sourceRealm}" \
               "${sourceToken}" \
               "${destBaseUrl}" \
               "${destRealm}" \
               "${destToken}" \
               "${clientId}"
    ;;

  copyclientroles)
    isCurlInstalled
    isJQInstalled

    sourceBaseUrl=${1:-https://dev.oidc.gov.bc.ca}
    sourceRealm=${2:-tz0e228w}
    sourceToken=""
    tokenUrl=$(getTokenUrl "${sourceBaseUrl}" "${sourceRealm}")
    getAuthToken "${tokenUrl}" "${sourceClientId}" "${sourceClientSecret}" "${!sourceToken@}"

    destBaseUrl=${3:-https://dev.loginproxy.gov.bc.ca}
    destRealm=${4:-court-services-jag}
    destToken=""
    tokenUrl=$(getTokenUrl "${destBaseUrl}" "${destRealm}")
    getAuthToken "${tokenUrl}" "${destClientId}" "${destClientSecret}" "${!destToken@}"

    clientId=${5:-ai-reviewer-api}

    copyClientRoles "${sourceBaseUrl}" \
                    "${sourceRealm}" \
                    "${sourceToken}" \
                    "${destBaseUrl}" \
                    "${destRealm}" \
                    "${destToken}" \
                    "${clientId}"
    ;;

  getusers)
    isCurlInstalled
    isJQInstalled

    baseUrl=${1:-https://dev.loginproxy.gov.bc.ca}
    realm=${2:-access-to-court-materials-jag}
    token=""
    tokenUrl=$(getTokenUrl "${baseUrl}" "${realm}")
    getAuthToken "${tokenUrl}" "${clientId}" "${clientSecret}" "${!token@}"

    searchQuery=${3}

    getUsers "${baseUrl}" \
              "${realm}" \
              "${token}" \
              "${searchQuery}"
    ;;

  deleteusers)
    isCurlInstalled
    isJQInstalled

    baseUrl=${1:-https://dev.loginproxy.gov.bc.ca}
    realm=${2:-access-to-court-materials-jag}
    token=""
    tokenUrl=$(getTokenUrl "${baseUrl}" "${realm}")
    getAuthToken "${tokenUrl}" "${clientId}" "${clientSecret}" "${!token@}"

    searchQuery=${3}

    deleteUsers "${baseUrl}" \
              "${realm}" \
              "${token}" \
              "${searchQuery}"
    ;;

  *)
    echoWarning "Unrecognized command; ${_cmd}"
    usage
    ;;
esac

popd >/dev/null