@startuml

:**Error Messages from BC Registries Audit Notification Received**;
start
:Confirm the alert by browsing to ""Orgbook.gov.bc.ca"" and search the company 
corporated number to verify the alert received in BC Registries Audit Notification
is not false positive by ensuring the data of Orgbook matches with BC Registries;
if (Issue Confirmed) then (yes)
  :Log into the affected OCP environment;
  :Run orgbook-configration \n./manage deleteTopic \nscript(s) as indicated by the audit notifications; 
  :Run von-bc-registries-agent-configurations \n./manage requeueOrganization \nscript(s) as indicated by the audit notifications;
  :Run von-bc-registries-agent-configurations \n./manage runPipeline \nscript;
  :Verify the indicated issue is resolved by browsing to orgbook.gov.bc.ca;
  else (no)
    :Timing issue;
endif
stop
@enduml
