@startuml

:**Credential Verification Alert Notification Received**;
start
:Confirm the alert by clicking on the 
""/api/credential/{credentialId}/verify""
in the alert.;
if (Responce contains: \n"""success": true"") then (no)
  :Log into the affected OCP environment.;
  repeat :Review the state of the Agent and Wallet pods.\n//Using the **Developer Topology** view works best.//;
    if(Issues with the Wallet Pod?) then (yes)
      :Resolve the issues with the Wallet pod.
      **Recycle** or **Rollout** if needed.

      A rollout can help get a pod to be
      scheduled on an new node in the case 
      the pod is stuck pending or starting on
      and overloaded node after an unexpected 
      restart or evacuation.;
      :Ensure the Wallet database is
      fully up and running.
      You won't be able to resolve any issues
      with the agents until the database is
      available.;
    else (no)
    endif
    if(Issues with the Agent Pods?) then (yes)
      :Resolve the issues with the Agent pods.
      **Rollout** if needed.
      
      A rollout can help get a pod to be
      scheduled on an new node in the case 
      the pod is stuck pending or starting on
      and overloaded node after an unexpected 
      restart or evacuation.;
    else (no)
    endif
    if(Issues with the API Pods?) then (yes)
      :Resolve the issues with the API pods.
      **Rollout** if needed.
      
      A rollout can help get a pod to be
      scheduled on an new node in the case 
      the pod is stuck pending or starting on
      and overloaded node after an unexpected 
      restart or evacuation.;
    else (no)
    endif
  repeat while (Alert cleared?) is (no) not (yes)
else (yes)
    :Transient issue or false positive.;
    :Monitor for a while to see if the issues
    persist.;
endif
stop
@enduml
