apiVersion: ops.gov.bc.ca/v1alpha1
kind: SysdigTeam
metadata:
  name: a99fd4-sysdigteam
  namespace: a99fd4-tools
spec:
  team:
    description: The Sysdig Team for the OpenShift Project Set a99fd4
    users:
      - name: wade@neoterictech.ca
        role: ROLE_TEAM_MANAGER

      - name: emiliano.sune@gmail.com
        role: ROLE_TEAM_MANAGER

      - name: ipzent@gmail.com
        role: ROLE_TEAM_EDIT
