apiVersion: ops.gov.bc.ca/v1alpha1
kind: SysdigTeam
metadata:
  name: bc0192-sysdigteam
  namespace: bc0192-tools
spec:
  team:
    description: The Sysdig Team for the OpenShift Project Set bc0192
    users:
      - name: wade@neoterictech.ca
        role: ROLE_TEAM_MANAGER

      - name: emiliano.sune@gmail.com
        role: ROLE_TEAM_MANAGER

      - name: ipzent@gmail.com
        role: ROLE_TEAM_EDIT

      - name: lucasoneil@gmail.com
        role: ROLE_TEAM_EDIT
