apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: certbot
  
resources:
  - buildconfig.yaml
  - cronjob.yaml
  - imagestream.yaml
  - pvc.yaml
  - role.yaml
  - rolebinding.yaml
  - secret.yaml
  - serviceaccount.yaml
