@startuml

:**BCovrin Down Notification Received**;
start

if (Do you have SSH access to the affected 
**von-network** environment?) then (yes)
  :Check the Validator Node Status at 
  **http://<env>.bcovrin.vonx.io/**;
  if(All 4 nodes appear?) then (yes)
    :Transient issue or false positive.;
    :Monitor for a while to see if the issues
    persist.;
  else (no)
    :SSH into the affected **von-network** environment;
    repeat :run **./restart-von-network**;
      :Monitor until **BCovrin** has finished
      restarting.;
      backward :Review logs to determine start-up failure.; 
      note right
        Timing issues on startup are the
        most common problem.
        If the issue can't be resolved 
        easily, stop and get help.
      end note
    repeat while (**BCovrin** started successfully, and the alert has cleared?) is (no) not (yes)
  endif
else (no)
  :Ensure someone with SSH access
  has been notified.;
endif

stop
@enduml
